name: Check-Universal
on: [push, pull_request]

jobs:
  validar-codigo: # Este es el nombre que tenés que buscar en 'Add checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Linter
        run: npm run lint || echo "No hay linter configurado aún"

      - name: Ejecutar Tests
        run: npm test || echo "No hay tests configurados aún"